services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=marketplacedb'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=root'
    expose:
      - '3306'